name = "ExampleMonorepo"
uuid = "0f595f7f-271a-49d7-b31d-0f5ff0a9189a"
authors = ["Mason Protter <mason.protter@icloud.com>"]
version = "0.1.0"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[weakdeps]
Stub1 = "e7278e9f-96f8-4b00-8276-224ecdc3ad49"

[extensions]
Submodule1 = "Stub1"

[compat]
PrecompileTools = "1.2.1"
UUIDs = "1.11.0"
